### ISSUE TITLE
Oscar isn't picking up my checkout app override

### ISSUE THREAD

**Issue by jonhairston** [django-oscar/django-oscar#1492]
Hello all, 

Im trying to customize Oscar checkout for a Stripe payment integration by overriding the checkout app. I'm trying to implement what these guys have here : https://github.com/redpandalabs/django-oscar-stripe. When i ran their sandbox, it runs fine with no problem; oscar recognizes the override and we're good to go.

I am currently working with django-cms, zinnia, and oscar to make a super beefy ecommerce site with blogging and content management with django cms on top of zinnia and oscar as in Oscar and Zinnia are Pages in my cms.

The problem is that oscar isn't seeing my overridden checkout app, even though get_core_apps returns apps.checkout when i throw a print statement or two in there.

i've followed the docs to the letter and what the guys have done at redpandalabs isn't too far off even though its dated.

my traceback:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_instance = mw_class()
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/jon/repos/amusement_wraps/amused/urls.py", line 19, in <module>
    url(r'^store/', include(store.urls)),
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/oscar/core/application.py", line 107, in urls
    return self.get_urls(), self.app_name, self.name
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/oscar/app.py", line 30, in get_urls
    (r'^checkout/', include(self.checkout_app.urls)),
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/oscar/core/application.py", line 107, in urls
    return self.get_urls(), self.app_name, self.name
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/oscar/apps/checkout/app.py", line 43, in get_urls
    self.payment_details_view.as_view(), name='payment-details'),
  File "/Users/jon/repos/amusement_wraps/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 11, in __get__
    raise AttributeError("This method is available only on the view class.")
AttributeError: This method is available only on the view class.
[18/Sep/2014 23:18:31] "GET / HTTP/1.1" 500 59
```

i get this when i use the shop.urls (as in redpandalabs app) instead of the default application.urls.

and when i use the default application.urls everything works nicely until my overridden checkout.views never gets called so my Stripe authentication never works, thus a payment is never recieved until the order gets processed if/when I hard code my Stripe key into the form instead of using env variables.

So for now instead of just forking an app ill have to copy the entirety of oscar and edit it that way since it won't see my overrides.

**Comment by sasha0** [comment]
Closing since it's lacking feedback a while and does not seem to be relevant any more. Please re-open in case of new questions/issues. Thanks!
