### ISSUE TITLE
Category data migration throws an error

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1689]
I just migrated my local Oscar installation and the recent [data migration](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/migrations/0003_data_migration_slugs.py) on categories threw an AttributeError on ``Category._slug_separator``. I think I don't fully understand what model I have at that point in time.

No stacktrace because I was on a train and writing down from memory.

**Comment by mvantellingen** [comment]
As far as I know datamigrations use custom models to represent the data. So custom properties (like `_slug_separator`) are not available.

**Comment by maikhoepfel** [comment]
Okay, to recreate:
```
# Check out a commit before the category changes
$ git checkout 63ee6e847119ec69e24d4563b6d2dddc254ae86a
# Create a new database
$ make sandbox
# Jump to a commit after the changes
$ git checkout master
# and try running the migrations
$ sites/sandbox/manage.py migrate
```

Stacktrace:
```
  Applying catalogue.0003_data_migration_slugs...Traceback (most recent call last):
  File "sites/sandbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/m/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/m/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/m/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/m/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/m/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/m/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/m/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/m/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/m/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/home/m/gits/django-oscar/django-oscar/src/oscar/apps/catalogue/migrations/0003_data_migration_slugs.py", line 10, in remove_ancestor_slugs
    category.slug = category.slug.split(Category._slug_separator)[-1]
AttributeError: type object 'Category' has no attribute '_slug_separator'
```

**Comment by vovanbo** [comment]
@sasha0 @codeinthehole Backward migration in [this commit](4fbadf8060bbcac27e22607089d6bb1f3e59f1a7) is still broken, because of MigrationCategory doesn't have ```full_slug``` property.

**Comment by sasha0** [comment]
I'll fix. Thanks.

**Comment by sasha0** [comment]
@codeinthehole @maikhoepfel @maikhoepfel Fixed, please take a look. Thanks.

**Comment by codeinthehole** [comment]
Sounds like this is complete now that 60b136f is in master - closing.

**Comment by sasha0** [comment]
@codeinthehole Not quite - https://github.com/django-oscar/django-oscar/pull/1775

**Comment by codeinthehole** [comment]
Ah - was tricked as the commit said 'master' next to it. That meant 'master' in your fork. My bad.

Now merged.
