### ISSUE TITLE
Sortable on Range products_view broken

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1853]
JQuery UI was removed here: https://github.com/django-oscar/django-oscar/commit/1af6521ab5a6a1891e09f78f6cfd90a55f5e8020

If you go to `products_view` (`/dashboard/ranges/3/products/`) you get a javascript error: `$(...).sortable is not a function`

**Comment by sasha0** [comment]
@john-parton thanks for the report. I'll prepare a fix.

**Comment by sasha0** [comment]
@mvantellingen please review.

**Comment by mvantellingen** [comment]
Hi @sasha0,

This results in the following exception for me in a new sandbox env:

    [2015-11-22 11:14:20,355] Internal Server Error: /en-gb/dashboard/ranges/2/reorder/
    Traceback (most recent call last):
      File "/usr/local/opt/pyenv/versions/oscar/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/opt/pyenv/versions/oscar/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
        return func(*args, **kwargs)
      File "/usr/local/opt/pyenv/versions/oscar/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
        return view_func(request, *args, **kwargs)
      File "/usr/local/opt/pyenv/versions/oscar/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
        return self.dispatch(request, *args, **kwargs)
      File "/usr/local/opt/pyenv/versions/oscar/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
        return handler(request, *args, **kwargs)
      File "/Users/mvantellingen/projects/opensource/django-oscar/src/oscar/apps/dashboard/ranges/views.py", line 204, in post
        self._save_page_order(order)
      File "/Users/mvantellingen/projects/opensource/django-oscar/src/oscar/apps/dashboard/ranges/views.py", line 213, in _save_page_order
        entry = RangeProduct.objects.get(range=range, product__pk=item)
      File "/usr/local/opt/pyenv/versions/oscar/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/usr/local/opt/pyenv/versions/oscar/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
        self.model._meta.object_name
    DoesNotExist: RangeProduct matching query does not exist.

**Comment by sasha0** [comment]
Actually, there's more than that. Found another one - there're duplicated products for range with included categories:
![2015-11-25 00 46 04](https://cloud.githubusercontent.com/assets/673711/11383052/33824220-930e-11e5-8ab6-5d1ea58a376f.png)
Also, if you delete product from this range, it will still remain in the list, because it's still has given category and included to the range within it.

**Comment by mvantellingen** [comment]
@sasha0 Thanks for the problem description. I think the most pragmatic solution for now is to only allow re-orderingen the products if they are explicitly added

**Comment by sasha0** [comment]
@mvantellingen thanks for the suggestion - I used it. Also included fixes for product duplication and product removal from range, explained in my previous comment. Please take a look.
