### ISSUE TITLE
Documentation Error: django.core.exceptions.ImproperlyConfigured: COMPRESS_ROOT defaults to STATIC_ROOT, please define either

### ISSUE THREAD

**Issue by sumanau7** [django-oscar/django-oscar#1918]
After following Installation Instructions directly from the page: http://django-oscar.readthedocs.org/en/latest/internals/getting_started.html

Command <b>python manage.py migrate<b> fails with following traceback.
```
/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/haystack/utils/__init__.py:12: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/compressor/models.py", line 1, in <module>
    from compressor.conf import CompressorConf  # noqa
  File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/compressor/conf.py", line 9, in <module>
    class CompressorConf(AppConf):
  File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/appconf/base.py", line 75, in __new__
    new_class._configure()
  File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/appconf/base.py", line 104, in _configure
    value = callback(value)
  File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/compressor/conf.py", line 91, in configure_root
    'STATIC_ROOT, please define either')
django.core.exceptions.ImproperlyConfigured: COMPRESS_ROOT defaults to STATIC_ROOT, please define either
```

If i add ```STATIC_ROOT = "/home/static_files/" ```

the migration is successful but runserver throws exception: 
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8001/

Django Version: 1.8.6
Python Version: 2.7.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.flatpages',
 'compressor',
 'widget_tweaks',
 'oscar',
 'oscar.apps.analytics',
 'oscar.apps.checkout',
 'oscar.apps.address',
 'oscar.apps.shipping',
 'oscar.apps.catalogue',
 'oscar.apps.catalogue.reviews',
 'oscar.apps.partner',
 'oscar.apps.basket',
 'oscar.apps.payment',
 'oscar.apps.offer',
 'oscar.apps.order',
 'oscar.apps.customer',
 'oscar.apps.promotions',
 'oscar.apps.search',
 'oscar.apps.voucher',
 'oscar.apps.wishlists',
 'oscar.apps.dashboard',
 'oscar.apps.dashboard.reports',
 'oscar.apps.dashboard.users',
 'oscar.apps.dashboard.orders',
 'oscar.apps.dashboard.promotions',
 'oscar.apps.dashboard.catalogue',
 'oscar.apps.dashboard.offers',
 'oscar.apps.dashboard.partners',
 'oscar.apps.dashboard.pages',
 'oscar.apps.dashboard.ranges',
 'oscar.apps.dashboard.reviews',
 'oscar.apps.dashboard.vouchers',
 'oscar.apps.dashboard.communications',
 'oscar.apps.dashboard.shipping',
 'haystack',
 'treebeard',
 'sorl.thumbnail',
 'django_tables2']
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'oscar.apps.basket.middleware.BasketMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware')

Template Loader Error:
Django tried loading these templates, in this order:
Using loader django.template.loaders.filesystem.Loader:
Using loader django.template.loaders.app_directories.Loader:
/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/contrib/admin/templates/promotions/home.html (File does not exist)
/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/contrib/auth/templates/promotions/home.html (File does not exist)
/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/compressor/templates/promotions/home.html (File does not exist)
/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/oscar/templates/promotions/home.html (File does not exist)
/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/haystack/templates/promotions/home.html (File does not exist)
/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/treebeard/templates/promotions/home.html (File does not exist)
/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django_tables2/templates/promotions/home.html (File does not exist)



Traceback:
File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  164.                 response = response.render()
File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/template/response.py" in render
  158.             self.content = self.rendered_content
File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/template/response.py" in rendered_content
  133.         template = self._resolve_template(self.template_name)
File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/template/response.py" in _resolve_template
  88.         new_template = self.resolve_template(template)
File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/template/response.py" in resolve_template
  78.             return loader.select_template(template, using=self.using)
File "/home/env/virtualenvs/myenv/local/lib/python2.7/site-packages/django/template/loader.py" in select_template
  76.         raise TemplateDoesNotExist(', '.join(template_name_list))

Exception Type: TemplateDoesNotExist at /
Exception Value: promotions/home.html
```

<b>pip freeze output: </b>
```
Babel==1.3
Django==1.8.6
django-appconf==1.0.1
django-compressor==1.6
django-extra-views==0.6.4
django-haystack==2.3.2
django-oscar==1.1.1
django-tables2==1.0.4
django-treebeard==3.0
django-widget-tweaks==1.3
factory-boy==2.4.1
mock==1.0.1
phonenumbers==6.3.0
Pillow==2.7.0
purl==1.1
pysolr==3.3.3
pytz==2015.7
requests==2.8.1
six==1.10.0
sorl-thumbnail==12.2
Unidecode==0.4.18
wheel==0.24.0

```

Is there anything which i am missing ?

I also did ``` python manage.py collectstatic ```  but the issue is still there.

**Comment by vrtt** [comment]
Remember you need to define in settings.py:
```
STATIC_ROOT = 'static'
STATIC_URL = '/static/'
MEDIA_ROOT = 'media'
MEDIA_URL = '/media/'
```

**Comment by sumanau7** [comment]
@vrtt Many thanks. It works now, last edition was from oscar import OSCAR_MAIN_TEMPLATE_DIR
but got that from the documentation link someone pasted in another issue.

**Comment by jorgebg** [comment]
Thanks @vrtt, it worked :)

**Comment by JakeTun** [comment]
Thank you very much @vrtt Oki Husso . now i can solve ....

**Comment by Darshan4114** [comment]
Thanks bud you great:)
