### ISSUE TITLE
Make sandbox installs Django 1.9

### ISSUE THREAD

**Issue by Botir** [django-oscar/django-oscar#1928]
To reproduce:
 >
`git clone https://github.com/django-oscar/django-oscar.git`
`cd django-oscar`
`virtualenv oscar`
`source ./oscar/bin/activate`
 `make sandbox`
**......**
**....**
`Running migrations:`
...
`Applying wishlists.0001_initial... OK`
>

 ```
Traceback (most recent call last):
  File "sites/sandbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/botir/Desktop/projects/dj-oscar/django-oscar/oscar/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/botir/Desktop/projects/dj-oscar/django-oscar/oscar/lib/python3.4/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/botir/Desktop/projects/dj-oscar/django-oscar/oscar/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/botir/Desktop/projects/dj-oscar/django-oscar/oscar/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/botir/Desktop/projects/dj-oscar/django-oscar/oscar/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 208, in handle
    changes = autodetector.changes(graph=executor.loader.graph)
  File "/home/botir/Desktop/projects/dj-oscar/django-oscar/oscar/lib/python3.4/site-packages/django/db/migrations/autodetector.py", line 43, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/home/botir/Desktop/projects/dj-oscar/django-oscar/oscar/lib/python3.4/site-packages/django/db/migrations/autodetector.py", line 186, in _detect_changes
    self.generate_altered_fields()
  File "/home/botir/Desktop/projects/dj-oscar/django-oscar/oscar/lib/python3.4/site-packages/django/db/migrations/autodetector.py", line 850, in generate_altered_fields
    if old_field_dec != new_field_dec:
  File "/home/botir/Desktop/projects/dj-oscar/django-oscar/oscar/lib/python3.4/site-packages/django/core/validators.py", line 55, in __eq__
    self.regex.pattern == other.regex.pattern and
AttributeError: 'bytes' object has no attribute 'pattern'
Makefile:8: recipe for target 'build_sandbox' failed
make: *** [build_sandbox] Error 1

```

__why make install doesn't install it.__

**Comment by sasha0** [comment]
What Django version currently installed in your environment?

**Comment by Botir** [comment]
after error i checked Django version with pip , i saw django=1.9
then i install django=1.8.5 and i tried again , and got the same error
, now django version = 1.8.5

**Comment by maikhoepfel** [comment]
Hi, I can confirm with the release of Django 1.9, after we call `make sandbox`, we end up with Django 1.9, which then causes the traceback above or the following: 

```
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'treebeard.templatetags.admin_tree': No module named 'django.contrib.admin.util'
make: *** [build_sandbox] Error 1
```

Until this is fixed, the workaround is to do the following:
```
$ make install
$ pip install Django==1.8.7
$ make build_sandbox
```

**Comment by Botir** [comment]
thanks all,
it is working only with sqlite
but with Mysql not working

>  File "/home/botir/Desktop/projects/ecommerce/django-oscar/oscar/lib/python3.4/site-packages/django/core/validators.py", line 55, in __eq__
    self.regex.pattern == other.regex.pattern and
AttributeError: 'bytes' object has no attribute 'pattern'
Makefile:8: recipe for target 'build_sandbox' failed
make: *** [build_sandbox] Error 1
>

**Comment by mvantellingen** [comment]
This is my fault. The master branch is marked compatible with Django 1.9 while treebeard doesn't support it yet. There are some PR's for treebeard at https://github.com/tabo/django-treebeard/pulls which you can try in the meantime.

**Comment by Botir** [comment]
vantellingen thanks very much, i will tried

**Comment by mvantellingen** [comment]
This is fixed for now via https://github.com/django-oscar/django-oscar/commit/b1477bf2476f865c78322e99db6db6b331403543
