### ISSUE TITLE
Promotions template bug with OrderedProduct

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1960]
The sandbox site is choking at the moment with the following stacktrace:

```
ERROR 2016-01-03 22:45:12,349 base Internal Server Error: /en-gb/
Traceback (most recent call last):
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/var/www/oscar/virtualenvs/latest/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/var/www/oscar/builds/latest/src/oscar/templatetags/promotion_tags.py", line 13, in render
    template = select_template([promotion.template_name(),
AttributeError: 'OrderedProduct' object has no attribute 'template_name'
```

This `OrderedProduct` is loaded from `sites/_fixtures/promotions.json` but can't be rendered correctly. I imagine something has changed recently with how promotions are rendered within the `promotion_tags` module.

**Comment by mvantellingen** [comment]
The issue was actually that the promotions.json data was invalid. Fixed via https://github.com/django-oscar/django-oscar/commit/4934db1f924c2be997640c97b8130b88a747247f
