### ISSUE TITLE
Docker image fails to build due to comments in requirements.txt

### ISSUE THREAD

**Issue by derek-adair** [django-oscar/django-oscar#2058]
Just wondering if any of ya'll are having issue's building the docker image?   pip is throwing an error.

 ```
---> 209077028996
Removing intermediate container 8a1d2bf52048
Step 5 : RUN pip install -r /requirements.txt
 ---> Running in e64a99a10551
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 287, in run
    wheel_cache
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 289, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_file.py", line 84, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 414, in get_file_content
    content = auto_decode(f.read())
  File "/usr/local/lib/python2.7/site-packages/pip/utils/encoding.py", line 23, in auto_decode
    return data.decode(locale.getpreferredencoding(False))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 303: ordinal not in range(128)
```

Very... very likely an issue with the python:2.7 image or... something, i'm not sure enitrely.  

However, i'm filing in this repo because the image seems to work peachy after removing **ALL** of the comments in the requirements.txt.  Obvious and heavy handed solution would be to add a requirements-docker.txt w/o comments.

**Comment by sasha0** [comment]
Just tried to build Docker image, but did not get this particular error (got another one though).

Please specify how did you try to build this image.

Thanks.

**Comment by derek-adair** [comment]
Very odd, I re-ran `make sandbox_image` and it worked just fine.  Presumably something with my VM, or my docker image got into a weird state?  Hard to say b/c my old VM i ran this against crashed on a power outage.

Closing tho, thanks for your response.
