### ISSUE TITLE
Django 1.9 upgrade migrations fail

### ISSUE THREAD

**Issue by Nuruddinjr** [django-oscar/django-oscar#2173]
I am upgrading django to 1.9 and Oscar to 1.3(from 1.2.1) and migration gives following error 

``` Applying catalogue.0009_auto_20160902_1953...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/db/migrations/operations/models.py", line 359, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 318, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/Users/nuruddin/.virtualenvs/magaz/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 347, in _delete_composed_index
    ", ".join(columns),
ValueError: Found wrong number (3) of constraints for catalogue_attributeoption(group_id, option)
```

**Comment by solarissmoke** [comment]
Closing as this appears to be an issue with your project rather than Oscar core. You might be able to get help on the mailing list.
