### ISSUE TITLE
LookupError: No installed app with label 'reviews'.

### ISSUE THREAD

**Issue by aravind12345** [django-oscar/django-oscar#2178]
After installing django, when i try to create a new project,the error is coming, 

```python
Unhandled exception in thread started by <function wrapper at 0x10910faa0>
Traceback (most recent call last):
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/voonik/python_env/django-oscar/teeshop/teeshop/urls.py", line 19, in <module>
    from oscar.app import application
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/app.py", line 13, in <module>
    class Shop(Application):
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/app.py", line 16, in Shop
    catalogue_app = get_class('catalogue.app', 'application')
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/core/loading.py", line 29, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/core/loading.py", line 86, in get_classes
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/core/loading.py", line 121, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/apps/catalogue/app.py", line 3, in <module>
    from oscar.apps.catalogue.reviews.app import application as reviews_app
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/apps/catalogue/reviews/app.py", line 8, in <module>
    class ProductReviewsApplication(Application):
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/apps/catalogue/reviews/app.py", line 12, in ProductReviewsApplication
    detail_view = get_class('catalogue.reviews.views', 'ProductReviewDetail')
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/core/loading.py", line 29, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/core/loading.py", line 86, in get_classes
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/core/loading.py", line 121, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/apps/catalogue/reviews/views.py", line 13, in <module>
    ['ProductReviewForm', 'VoteForm', 'SortReviewsForm'])
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/core/loading.py", line 86, in get_classes
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/core/loading.py", line 121, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/apps/catalogue/reviews/forms.py", line 6, in <module>
    Vote = get_model('reviews', 'vote')
  File "/Users/voonik/python_env/lib/python2.7/site-packages/oscar/core/loading.py", line 235, in get_model
    return apps.get_model(app_label, model_name)
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/apps/registry.py", line 197, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/Users/voonik/python_env/lib/python2.7/site-packages/django/apps/registry.py", line 155, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'reviews'.
```

**Comment by eve1234** [comment]
Hi,

I have same error.

**Comment by soogly** [comment]
+1

**Comment by alcfernandes** [comment]
+1

**Comment by alcfernandes** [comment]
Try this

```
from oscar import get_core_apps

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
     'compressor',
] + get_core_apps()
```

**Comment by kooba** [comment]
This happened to me when I didn't add core apps to the `INSTALLED_APPS`.

Should be:
```
INSTALLED_APPS = [
   ...
] + get_core_apps()
```

**Comment by mvantellingen** [comment]
That should indeed be the issue. Thanks @kooba

**Comment by daugela** [comment]
Just solved the same issue after noticing another missing configuration:
**from oscar import OSCAR_MAIN_TEMPLATE_DIR**
TEMPLATES = [
{
DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            **OSCAR_MAIN_TEMPLATE_DIR**
        ],
