### ISSUE TITLE
python manage.py oscar_populate_countries throws error -

### ISSUE THREAD

**Issue by eve1234** [django-oscar/django-oscar#2183]
Hello,

while running the following command I get this error -

`./manage.py oscar_populate_countries`

or

`python manage.py oscar_populate_countries -
`

This' the log.

```
./manage.py oscar_populate_countries
/Users/akos/oscar/lib/python2.7/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/Users/akos/oscar/lib/python2.7/site-packages/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/akos/oscar/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/akos/oscar/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/akos/oscar/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/akos/oscar/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/akos/oscar/lib/python2.7/site-packages/oscar/management/commands/oscar_populate_countries.py", line 58, in handle
    for country in pycountry.countries]
  File "/Users/akos/oscar/lib/python2.7/site-packages/pycountry/db.py", line 22, in __getattr__
    raise AttributeError
AttributeError


```

I have been google to find the answer. And evening ended up creating a whole new project again. What Im I doing wrong?

Regards

**Comment by adlh** [comment]
Same for me on a 100% fresh installation. 

These are my installed packages in the venv:
```
$ pip freeze
Babel==2.3.4
Django==1.9
django-extra-views==0.6.4
django-haystack==2.5.1
django-oscar==1.3
django-tables2==1.0.7
django-treebeard==4.1.0
django-widget-tweaks==1.4.1
factory-boy==2.8.1
Faker==0.7.5
mock==2.0.0
pbr==1.10.0
phonenumbers==7.7.5
Pillow==3.4.2
purl==1.3
pycountry==16.11.27.1
python-dateutil==2.6.0
pytz==2016.10
six==1.10.0
sorl-thumbnail==12.4a1
Unidecode==0.4.19
```

**Comment by zt-initech** [comment]
pycountry changes its API and its versioning scheme.
You can also make a fix for 1.3.

**Comment by eve1234** [comment]
I had to hack the file, made changes to make to works some weeks back.

check this thread

https://groups.google.com/forum/#!topic/django-oscar/_Tfwlnvr43s

regards

**Comment by solarissmoke** [comment]
Fixed in https://github.com/django-oscar/django-oscar/pull/2199
