### ISSUE TITLE
manage.py oscar_populate_countries fails with AttributeError

### ISSUE THREAD

**Issue by thomaskr** [django-oscar/django-oscar#2204]
Using the management command `oscar_populate_countries` results in a messageless AttributeError:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vwfs/.virtualenvs/web-shop/lib/python3.5/site-packages/pydevd.py", line 1537, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/vwfs/.virtualenvs/web-shop/lib/python3.5/site-packages/pydevd.py", line 976, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/vwfs/.virtualenvs/web-shop/lib/python3.5/site-packages/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vwfs/.virtualenvs/web-shop/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/vwfs/.virtualenvs/web-shop/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vwfs/.virtualenvs/web-shop/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vwfs/.virtualenvs/web-shop/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/vwfs/.virtualenvs/web-shop/lib/python3.5/site-packages/oscar/management/commands/oscar_populate_countries.py", line 58, in handle
    for country in pycountry.countries]
  File "/home/vwfs/.virtualenvs/web-shop/lib/python3.5/site-packages/oscar/management/commands/oscar_populate_countries.py", line 58, in <listcomp>
    for country in pycountry.countries]
  File "/home/vwfs/.virtualenvs/web-shop/lib/python3.5/site-packages/pycountry/db.py", line 22, in __getattr__
    raise AttributeError
AttributeError
```
Environment:

Django (1.9.12), django-oscar (1.3), pycountry (16.11.27.1)

Cause:

The management command tries to access the attributes `alpha2` and `alpha3` of the data returned by `pycountry` but they are actually named `alpha_2` and `alpha_3`.

**Comment by tobiase** [comment]
This issue duplicates #2183

**Comment by thomaskr** [comment]
Closing as duplicate.
