### ISSUE TITLE
Django Oscar doesn't see products

### ISSUE THREAD

**Issue by artemdumanov** [django-oscar/django-oscar#2263]
I was added a new category, then I was added product type, then I was added a product. [*screenshoot](https://i.stack.imgur.com/FrkSU.png)

I can see my new category, but there is no products at all [*screenshoot](https://i.stack.imgur.com/tVOg3.png)

But, I can view it on my site follow link localhost:8080/catalogue/zelenaia-kraska_6/ 
I get this link from dashboard (product -> actions -> view on site)

How to fix this problem? 

CONSOLE:
```python
`Failed to query Solr using '*:*': Failed to connect to server at 'http://127.0.0.1:8983/solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=1&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1', are you sure that URL is correct? Checking it in a browser might help: HTTPConnectionPool(host='127.0.0.1', port=8983): Max retries exceeded with url: /solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=1&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4c746459e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f4c746459e8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8983): Max retries exceeded with url: /solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=1&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4c746459e8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pysolr.py", line 366, in _send_request
    timeout=self.timeout)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8983): Max retries exceeded with url: /solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=1&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4c746459e8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/haystack/backends/solr_backend.py", line 134, in search
    raw_results = self.conn.search(query_string, **search_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/local/lib/python3.4/dist-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/local/lib/python3.4/dist-packages/pysolr.py", line 375, in _send_request
    raise SolrError(error_message % params)
pysolr.SolrError: Failed to connect to server at 'http://127.0.0.1:8983/solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=1&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1', are you sure that URL is correct? Checking it in a browser might help: HTTPConnectionPool(host='127.0.0.1', port=8983): Max retries exceeded with url: /solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=1&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4c746459e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
Failed to query Solr using '*:*': Failed to connect to server at 'http://127.0.0.1:8983/solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=0&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1', are you sure that URL is correct? Checking it in a browser might help: HTTPConnectionPool(host='127.0.0.1', port=8983): Max retries exceeded with url: /solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=0&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4c745e16d8>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f4c745e16d8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8983): Max retries exceeded with url: /solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=0&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4c745e16d8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pysolr.py", line 366, in _send_request
    timeout=self.timeout)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8983): Max retries exceeded with url: /solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=0&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4c745e16d8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/haystack/backends/solr_backend.py", line 134, in search
    raw_results = self.conn.search(query_string, **search_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "/usr/local/lib/python3.4/dist-packages/pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "/usr/local/lib/python3.4/dist-packages/pysolr.py", line 375, in _send_request
    raise SolrError(error_message % params)
pysolr.SolrError: Failed to connect to server at 'http://127.0.0.1:8983/solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=0&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1', are you sure that URL is correct? Checking it in a browser might help: HTTPConnectionPool(host='127.0.0.1', port=8983): Max retries exceeded with url: /solr/select/?spellcheck=true&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&rows=0&fl=%2A+score&facet=on&facet.field=rating_exact&facet.field=product_class_exact&q=%2A%3A%2A&spellcheck.collate=true&wt=json&start=0&fq=category_exact%3A%28%22%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5%22%29&fq=django_ct%3A%28catalogue.product%29&spellcheck.count=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4c745e16d8>: Failed to establish a new connection: [Errno 111] Connection refused',))
/usr/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango110Warning: django.core.context_processors is deprecated in favor of django.template.context_processors.
  return f(*args, **kwds)

[11/Mar/2017 20:34:38] "GET /catalogue/category/glavnoe_2/ HTTP/1.1" 200 25858
Not Found: /media/cache/17/d5/17d59725435216b0e455fcb9659a84f3.jpg
Internal Server Error: /media/cache/17/d5/17d59725435216b0e455fcb9659a84f3.jpg
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/sites/models.py", line 44, in _get_site_by_request
    SITE_CACHE[host] = self.get(domain__iexact=host)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
django.contrib.sites.models.DoesNotExist: Site matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/flatpages/middleware.py", line 11, in process_response
    return flatpage(request, request.path_info)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/flatpages/views.py", line 35, in flatpage
    site_id = get_current_site(request).id
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/sites/shortcuts.py", line 15, in get_current_site
    return Site.objects.get_current(request)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/sites/models.py", line 67, in get_current
    return self._get_site_by_request(request)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/sites/models.py", line 52, in _get_site_by_request
    SITE_CACHE[domain] = self.get(domain__iexact=domain)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
django.contrib.sites.models.DoesNotExist: Site matching query does not exist.
[11/Mar/2017 20:34:39] "GET /media/cache/17/d5/17d59725435216b0e455fcb9659a84f3.jpg HTTP/1.1" 500 128371
[11/Mar/2017 20:34:39] "GET /static/oscar/favicon.ico HTTP/1.1" 200 1150`
```

**Comment by jklapuch** [comment]
Try to compare your settings with django-oscar\sandbox\settings.py. Check configuration of HAYSTACK_CONNECTIONS, MEDIA_URL and MEDIA_ROOT.

**Comment by phares** [comment]
I am experiencing the same problem.

**Comment by jklapuch** [comment]
Does it work with
`HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
    },
}`
?

**Comment by phares** [comment]
Yes it just worked for me. i changed my settings to

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
        'URL': 'http://127.0.0.1:8000/solr/default',
        'INCLUDE_SPELLING': True,
    },
}

and the products just showed up

**Comment by jklapuch** [comment]
You could remove other Haystack settings except 'ENGINE'. If you want to use Apache Solr as search backend you should see [docs](http://django-oscar.readthedocs.io/en/latest/howto/how_to_setup_solr.html)

**Comment by SalahAdDin** [comment]
Are there problems with the last elasticsearch engine? I saw that `Haystack` added recently support for lastest version.

**Comment by okfish** [comment]
Check SITE_ID settings as said in logs:
> django.contrib.sites.models.DoesNotExist: Site matching query does not exist.

**Comment by SalahAdDin** [comment]
@okfish it is a very rarely problem.

**Comment by sasha0** [comment]
Agree with @jklapuch - this looks like a configuration issue, please refer to the documentation mentioned above. For the support issues you can use mailing list. Thanks.

**Comment by AMfalme** [comment]
I seem to be running into the same issue and I have been trying to find a solution for a couple of hours now unsuccessfully. I know this is a closed issue but I would appreciate some help here. Thanks.

**Comment by farhoodva** [comment]
this is still a problem for a lot of people!!

**Comment by Summer88** [comment]
There's a settiings that's not explained in docs:

OSCAR_PRODUCT_SEARCH_HANDLER = 'search.CustomSearchHandler'

I've added the search.CustomSearchHandler in the search/__init__.py 

```

from django.conf import settings
from oscar.apps.search.search_handlers import  SearchHandler
from oscar.apps.catalogue.models import Product, Category
from oscar.core.loading import get_class, get_model

FacetMunger = get_class('search.facets', 'FacetMunger')
BrowseCategoryForm = get_class('search.forms', 'BrowseCategoryForm')


class CustomSearchHandler(SearchHandler):
    form_class = BrowseCategoryForm
    model_whitelist = [Product]
    paginate_by = settings.OSCAR_PRODUCTS_PER_PAGE


    def __init__(self, request_data, full_path, categories=None):
        self.categories = Category.objects.all() #categories
        #breakpoint()
        super().__init__(request_data, full_path)
```
But I'm stuck here, without results. from shell this return results:
` Product.objects.filter(categories=Category.objects.last().pk)`

Is there an example to remove solr and hayastack and work with django default  capabilites https://docs.djangoproject.com/en/4.0/ref/contrib/postgres/search/?

**Comment by Summer88** [comment]
Anyway I've temporary fixed showing all products adding this line to :

`		search_context['products'] = Product.objects.all()`

https://github.com/django-oscar/django-oscar/blob/ffcc530844d40283b6b1552778a140536b904f5f/src/oscar/apps/catalogue/views.py#L147

before      `ctx.update(search_context)`.

This will show all products when calling URL http://host/catalogue/

**Comment by ciccio91** [comment]
Hi, in my environment with working Sorl as backend, if I fork the "search" app with the oscar_fork_app command, no products are found when reloading the index.

As I revert the commit to the original oscar app, the products are found as expected.

Do I have to modify some specific file to make the custom forked search app working?

Thank you all in advance for any help!

[requirements.txt](https://github.com/user-attachments/files/20042570/requirements.txt)
