### ISSUE TITLE
Authentication does not work

### ISSUE THREAD

**Issue by fazpu** [django-oscar/django-oscar#2361]
When I tried to do an initial setup of the application based on the documentation, I came across this error when trying to sign in to dashboard:

```
Internal Server Error: /dashboard/login/
Traceback (most recent call last):
  File "/home/eshop/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/eshop/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/eshop/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/eshop/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/eshop/env/lib/python3.5/site-packages/django/contrib/auth/views.py", line 54, in inner
    return func(*args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/contrib/auth/views.py", line 139, in login
    return LoginView.as_view(**kwargs)(request, *args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/eshop/env/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/eshop/env/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/eshop/env/lib/python3.5/site-packages/django/contrib/auth/views.py", line 90, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/eshop/env/lib/python3.5/site-packages/django/views/generic/edit.py", line 182, in post
    if form.is_valid():
  File "/home/eshop/env/lib/python3.5/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/home/eshop/env/lib/python3.5/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/home/eshop/env/lib/python3.5/site-packages/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/home/eshop/env/lib/python3.5/site-packages/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "/home/eshop/env/lib/python3.5/site-packages/django/contrib/auth/forms.py", line 187, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/home/eshop/env/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 100, in authenticate
    user = backend.authenticate(*args, **credentials)
  File "/home/eshop/env/lib/python3.5/site-packages/oscar/apps/customer/auth_backends.py", line 31, in authenticate
    clean_email = normalise_email(email)
  File "/home/eshop/env/lib/python3.5/site-packages/oscar/apps/customer/utils.py", line 130, in normalise_email
    clean_email = email.strip()
AttributeError: 'WSGIRequest' object has no attribute 'strip'
```

I am using Django 1.11 and in settings:

```
AUTHENTICATION_BACKENDS = (
    'oscar.apps.customer.auth_backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
)
```

**Comment by fazpu** [comment]
OK, got it.

The problem is in the EmailBackend.authenticate method, since there is one argument missing - **request**.

Instead of `authenticate(self, email=None, password=None, *args, **kwargs)` it should be `authenticate(self, request, email=None, password=None, *args, **kwargs)`

because of this calling line:
```
File "/home/eshop/env/lib/python3.5/site-packages/django/contrib/auth/forms.py", line 187, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
```

**Comment by fazpu** [comment]
The error seems to be resolved by https://github.com/django-oscar/django-oscar/pull/2321. It would be nice to make new release so that it is applied.

**Comment by solarissmoke** [comment]
You can install version `1.5rc1` which includes this fix.

**Comment by fazpu** [comment]
Thanks

**Comment by solarissmoke** [comment]
Closing as duplicated of #2321.
