### ISSUE TITLE
solr error. java.lang.RuntimeException: unknown field 'id'

### ISSUE THREAD

**Issue by joyzhang15** [django-oscar/django-oscar#2635]
I follow the instruction: [http://django-oscar.readthedocs.io/en/latest/howto/how_to_setup_solr.html](http://django-oscar.readthedocs.io/en/latest/howto/how_to_setup_solr.html)
And it raise Error:

> 2434 [coreLoadExecutor-4-thread-1] ERROR org.apache.solr.core.CoreContainer  – Unable to create core: collection1
org.apache.solr.common.SolrException: Schema Parsing Failed: unknown field 'id'. Schema file is D:\grit\solr-4.7.2\example\solr\collection1\schema.xml
        at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:618)
        at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:166)
        at org.apache.solr.schema.IndexSchemaFactory.create(IndexSchemaFactory.java:55)
        at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:69)
        at org.apache.solr.core.CoreContainer.createFromLocal(CoreContainer.java:559)
        at org.apache.solr.core.CoreContainer.create(CoreContainer.java:597)
        at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:258)
        at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:250)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: unknown field 'id'
        at org.apache.solr.schema.IndexSchema.getIndexedField(IndexSchema.java:340)
        at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:536)
        ... 13 more
2437 [coreLoadExecutor-4-thread-1] ERROR org.apache.solr.core.CoreContainer  – null:org.apache.solr.common.SolrException: Unable to create core: collection1
        at org.apache.solr.core.CoreContainer.recordAndThrow(CoreContainer.java:989)
        at org.apache.solr.core.CoreContainer.create(CoreContainer.java:606)
        at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:258)
        at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:250)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.solr.common.SolrException: Schema Parsing Failed: unknown field 'id'. Schema file is D:\grit\solr-4.7.2\example\solr\collection1\schema.xml
        at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:618)
        at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:166)
        at org.apache.solr.schema.IndexSchemaFactory.create(IndexSchemaFactory.java:55)
        at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:69)
        at org.apache.solr.core.CoreContainer.createFromLocal(CoreContainer.java:559)
        at org.apache.solr.core.CoreContainer.create(CoreContainer.java:597)
        ... 8 more
Caused by: java.lang.RuntimeException: unknown field 'id'
        at org.apache.solr.schema.IndexSchema.getIndexedField(IndexSchema.java:340)
        at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:536)
        ... 13 more

**Comment by asanka94** [comment]
Were you able to solve this issue?

**Comment by OndraRehounek** [comment]
I'm getting the same error. I was able to run Solr 7.3.0 without problems however there are no instructions how to set it with Oscar...

**Comment by MsMansiDhruv** [comment]
I am facing the same issue could you let me know how you were able to solve it? Documentation seems no help.

**Comment by OndraRehounek** [comment]
@MsMansiDhruv - we left Oscar long time and happilly using Saleor...

**Comment by MsMansiDhruv** [comment]
What were the technical issues that you personally faced and why did you choose Saleor over Oscar?

**Comment by solarissmoke** [comment]
Hi there - can I request that you have discussions about the merits of Oscar vs other platforms elsewhere - e.g., on https://softwarerecs.stackexchange.com/ ? (This isn't the right place to do so and creates noise for people who are watching this repository for development issues related to Oscar).

**Comment by arafay993** [comment]
I have also got the same error when I ran `java -jar start.jar`, but luckily I found a [ thread](https://groups.google.com/d/msg/django-oscar/8GmrtvDDdoQ/kLQLm286AQAJ) in Google Group. Now, my Solr 4.7.2 is up and running on **http://127.0.0.1:8983/solr/#/collection1**. This conversation will provide you a schema.xml file which you need to replace with schema.xml created after running command:
`./manage.py build_solr_schema > solr-4.7.2/example/solr/collection1/conf/schema.xml`
I have also attached the schema.zip
[schema.zip](https://github.com/django-oscar/django-oscar/files/3615500/schema.zip)

**Comment by MsMansiDhruv** [comment]
> I have also got the same error when I ran `java -jar start.jar`, but luckily I found a [ thread](https://groups.google.com/d/msg/django-oscar/8GmrtvDDdoQ/kLQLm286AQAJ) in Google Group. Now, my Solr 4.7.2 is up and running on **http://127.0.0.1:8983/solr/#/collection1**. This conversation will provide you a schema.xml file which you need to replace with schema.xml created after running command:
> `./manage.py build_solr_schema > solr-4.7.2/example/solr/collection1/conf/schema.xml`
> I have also attached the schema.zip
> [schema.zip](https://github.com/django-oscar/django-oscar/files/3615500/schema.zip)

Thanks I'll try working on this and let you know if it solved the issue for me.
