### ISSUE TITLE
super() takes at least 1 argument (0 given) - make: *** [sandbox_clean] Error 1

### ISSUE THREAD

**Issue by saman-com** [django-oscar/django-oscar#2746]
I received following error in the last step of installation. any idea:
Traceback (most recent call last):
  `File "sandbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/saman/Virtualenv/oscar/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/saman/Virtualenv/oscar/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/saman/Virtualenv/oscar/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/saman/Virtualenv/oscar/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/saman/Virtualenv/oscar/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/saman/Virtualenv/django-oscar/src/oscar/apps/address/models.py", line 1, in <module>
    from oscar.apps.address.abstract_models import (
  File "/Users/saman/Virtualenv/django-oscar/src/oscar/apps/address/abstract_models.py", line 16, in <module>
    class AbstractAddress(models.Model):
  File "/Users/saman/Virtualenv/oscar/lib/python2.7/site-packages/django/db/models/base.py", line 162, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/Users/saman/Virtualenv/oscar/lib/python2.7/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/saman/Virtualenv/django-oscar/src/oscar/models/fields/__init__.py", line 78, in contribute_to_class
    super().contribute_to_class(
TypeError: Error when calling the metaclass bases
    super() takes at least 1 argument (0 given)
make: *** [sandbox_clean] Error 1`

**Comment by solarissmoke** [comment]
We dropped support for Python 2 recently - you need to use Python 3 if you've cloned this repository.
