### ISSUE TITLE
Class loader throws an error after forking dashboard

### ISSUE THREAD

**Issue by kunkku** [django-oscar/django-oscar#3308]
## Issue Summary

Using a forked dashboard application results in an error.

## Steps to Reproduce

1. Set up an Oscar project named `foo` as described in the section titled "Building your own shop"
2. Run `./manage.py oscar_fork_app dashboard foo`
3. Substitute `foo.dashboard` for `oscar.apps.dashboard` in `foo/settings.py`
4. Run `./manage.py`

The following exception is thrown:

<pre>Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/lib/python3.8/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/lib/python3.8/site-packages/oscar/apps/dashboard/reports/apps.py", line 16, in ready
    self.index_view = get_class('dashboard.reports.views', 'IndexView')
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 31, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 41, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 99, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 133, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/lib/python3.8/site-packages/oscar/apps/dashboard/reports/views.py", line 9, in <module>
    ReportForm = get_class('dashboard.reports.forms', 'ReportForm')
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 31, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 41, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 99, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 133, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/lib/python3.8/site-packages/oscar/apps/dashboard/reports/forms.py", line 7, in <module>
    GeneratorRepository = get_class('dashboard.reports.utils',
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 31, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 41, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 99, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 133, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/lib/python3.8/site-packages/oscar/apps/dashboard/reports/utils.py", line 3, in <module>
    OrderReportGenerator = get_class('order.reports', 'OrderReportGenerator')
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 31, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 41, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 99, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 133, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/lib/python3.8/site-packages/oscar/apps/order/reports.py", line 7, in <module>
    ReportGenerator = get_class('dashboard.reports.reports', 'ReportGenerator')
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 31, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 41, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 104, in default_class_loader
    app_name = _find_registered_app_name(module_label)
  File "/usr/lib/python3.8/site-packages/oscar/core/loading.py", line 188, in _find_registered_app_name
    raise AppNotFoundError(
oscar.core.exceptions.AppNotFoundError: Couldn't find an Oscar app to import dashboard.reports.reports from
</pre>

## Technical Details

* Python version: 3.8.1
* Django version: 1.11.28
* Oscar version: 2.0.4

**Comment by solarissmoke** [comment]
I suspect this is because you haven't forked any of the dashboard's sub-apps? You need to fork at least one of those as well - e.g., you need `foo.dashboard.catalogue` to exist in addition to `foo.dashboard`.

**Comment by kunkku** [comment]
I did some further investigation on this. Forking additional dashboard applications did not solve the problem, but using`foo.dashbord.apps.DashboardConfig` in `INSTALLED_APPS` or adding
`default_app_config = foo.dashbord.apps.DashboardConfig` to `foo/dashboard/__init__.py` did the trick.

According to the section titled "Customising Oscar" in the documentation, using the module path should suffice. However, the current implementation of `oscar_fork_app` no longer sets `default_app_config`. Is there a good reason for not setting it?

**Comment by solarissmoke** [comment]
I think this was probably just an oversight. The documentation has been updated on master to [use the explicit app config](https://github.com/django-oscar/django-oscar/blob/master/docs/source/topics/customisation.rst), will try and get that onto readthedocs soon.

Leaving this open as a reminder to look into the `default_app_config`.
