### ISSUE TITLE
1093, "You can't specify target table 'catalogue_category' for update in FROM clause"

### ISSUE THREAD

**Issue by ngashdavis** [django-oscar/django-oscar#3335]
Found a bug? Please fill out the sections below.

### Issue Summary

I am trying to run database migration with the latest oscar to create a sandbox and I running into this error. This is by running 

make sandbox 

django.db.utils.InternalError: Problem installing fixture '/usr/local/app/django_python3/django-oscar/sandbox/fixtures/child_products.json': Could not load catalogue.Category(pk=1): (1093, "You can't specify target table 'catalogue_category' for update in FROM clause")
make: *** [sandbox_load_data] Error 1

### Steps to Reproduce

Traceback (most recent call last):
  File "/usr/local/app/django_python3/oscar/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/app/django_python3/oscar/local/lib/python3.6/dist-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/app/django_python3/oscar/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/app/django_python3/oscar/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/app/django_python3/oscar/local/lib/python3.6/dist-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/app/django_python3/oscar/local/lib/python3.6/dist-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/app/django_python3/oscar/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/app/django_python3/oscar/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/app/django_python3/oscar/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/app/django_python3/oscar/local/lib/python3.6/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1093, "You can't specify target table 'catalogue_category' for update in FROM clause")

### Technical details

(oscar) [ec2-user@ip-172-31-23-50 django-oscar]$ python --version
Python 3.6.8
(oscar) [ec2-user@ip-172-31-23-50 django-oscar]$ pip show django | grep Version
Version: 3.0.4
(oscar) [ec2-user@ip-172-31-23-50 django-oscar]$ pip show django-oscar | grep Version
Version: 2.0.1
(oscar) [ec2-user@ip-172-31-23-50 django-oscar]$

**Comment by ngashdavis** [comment]
When  i tried to google , I found this URL  we need to change the way the query is been made.  I am using MySQL database . 

(oscar) [ec2-user@ip-172-31-23-50 django-oscar]$ mysql -V
mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper
(oscar) [ec2-user@ip-172-31-23-50 django-oscar]$


https://www.inforbiro.com/blog/mysql-cant-specify-target-table-for-update-in-from-clause .

**Comment by solarissmoke** [comment]
Oscar doesn't currently support MySQL (see https://github.com/django-oscar/django-oscar/pull/2630 for some discussions on why this isn't likely to change any time soon). Also this error isn't caused by Oscar itself - but by Django when it loads a standard set of fixtures. It appears that Django too doesn't plan to fix this: https://code.djangoproject.com/ticket/28787 .

**Comment by ebrake** [comment]
I'm overriding the oscar model method to disable the method for mysql compatibility (since everything is public in our implementation), running on a large e-commerce site.
```
class Category(AbstractCategory):
    def set_ancestors_are_public(self):
        pass
```
