### ISSUE TITLE
Category management is broken for django-oscar 2.1.0

### ISSUE THREAD

**Issue by develucas** [django-oscar/django-oscar#3451]
### Issue Summary

After upgrading django-oscar to 2.1.0, categories seem to not work anymore. It is impossible to neither add new category nor change the existing ones. It's also affecting child categories as I couldn't delete them.
To be sure I've created new environment with fresh install and unfortunatelly it was occuring too. It is impossible to create first category whatsoever.

Everything related to django-oscar upgrade went without any problems. This is first time I'm experiencing something serious with oscar.
Remark: url for accessing dashboard is changed in my case

Exception comes to this:
```(1093, "You can't specify target table 'catalogue_category' for update in FROM clause")```

Here is the executed query:
```
(b'UPDATE `catalogue_category` SET `ancestors_are_public` = NOT EXISTS(SELECT U'  b'0.`id` FROM `catalogue_category` U0 WHERE (U0.`depth` < `catalogue_category`'  b'.`depth` AND U0.`is_public` = 0 AND `catalogue_category`.`path` LIKE BINARY '  b"CONCAT(REPLACE(REPLACE(REPLACE(U0.`path`, '\\\\', '\\\\\\\\'), '%', '\\%'),"  b" '_', '\\_'), '%'))) WHERE `catalogue_category`.`id` = 1")
```
Full traceback:

```python
Traceback (most recent call last):
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)

The above exception ((1093, "You can't specify target table 'catalogue_category' for update in FROM clause")) was the direct cause of the following exception:
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/treebeard/forms.py", line 147, in save
    self.instance = self._meta.model.add_root(**cl_data)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/treebeard/mp_tree.py", line 625, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/treebeard/mp_tree.py", line 345, in process
    newobj.save()
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/oscar/apps/catalogue/abstract_models.py", line 209, in save
    super().save(*args, **kwargs)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/models/base.py", line 795, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/oscar/apps/catalogue/receivers.py", line 37, in post_save_set_ancestors_are_public
    instance.set_ancestors_are_public()
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/oscar/apps/catalogue/abstract_models.py", line 220, in set_ancestors_are_public
    included_in_non_public_subtree.values("id"), negated=True))
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/models/query.py", line 752, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1500, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
    cursor.execute(sql, params)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/develucas/.virtualenv/temp/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)

Exception Type: OperationalError at /shkl6943pn6cy6sx/catalogue/categories/create/
Exception Value: (1093, "You can't specify target table 'catalogue_category' for update in FROM clause")
```

### Steps to Reproduce

1. Create new environment
2. Install django-oscar with all dependencies
3. Apply migrations, create superuser and populate countries
3. Go to dashboard
4. Create new category

### Technical details

* Django Version: 3.0.8
* Python Version: 3.6.8
* Oscar Version: 2.1.0

**Comment by solarissmoke** [comment]
This appears to be the same issue as #3335, which is not new to Oscar 2.1. I'm not able to reproduce the problem on master, or on the [sandbox](https://latest.oscarcommerce.com/) with postgresql. I think the comment made on #3335 and the Django ticket it references still apply - this is a a bug in mysql. If someone is able to come up with a workaround that isn't too complicated, I've no objection to incorporating it into Oscar.

**Comment by develucas** [comment]
@solarissmoke thank you for such a quick response. I read issues related to this one and it's a huge relief for me that it's not a bug in oscar. You have just gave me enough reason to switch to postgresql and start using it together with oscar always from now on. I'm going to confirm now that the issue is not a bug and I will close this afterwards.

Thank you very much for your support.
Best regards

**Comment by develucas** [comment]
I can confirm now that issue is related to RDBMS used and its limitations. It also occured that postgresql minimum version that should be used is 9.5 [as described in Django documentation](https://docs.djangoproject.com/en/3.0/ref/databases/#postgresql-notes).

I think this ticket can be closed.
