### ISSUE TITLE
Custom user model migration fail. SettingsReference object has no attribute '_meta'

### ISSUE THREAD

**Issue by thgazis** [django-oscar/django-oscar#3490]
**ISSUE SUMMARY**
When creating an custom user model with an extra field migration fail.

**STEPS TO REPRODUCE**
As described in Oscar's documention:

1) Create a user app
2) Subclass customer.AbstractUser to create the new User model
3) Add new field
4) Add AUTH_USER_MODEL = "user.User" settings
5) Run python manage.py makemigrations

The output should be:

`Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/thanasis/projects/naturaldoctor/natural-doctor/virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/thanasis/projects/naturaldoctor/natural-doctor/virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/thanasis/projects/naturaldoctor/natural-doctor/virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/thanasis/projects/naturaldoctor/natural-doctor/virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/thanasis/projects/naturaldoctor/natural-doctor/virtualenv/lib/python3.6/site-packages/wagtail_modeltranslation/management/commands/makemigrations_translation.py", line 27, in handle
    super(Command, self).handle(*args, **options)
  File "/home/thanasis/projects/naturaldoctor/natural-doctor/virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/thanasis/projects/naturaldoctor/natural-doctor/virtualenv/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 168, in handle
    migration_name=self.migration_name,
  File "/home/thanasis/projects/naturaldoctor/natural-doctor/virtualenv/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 43, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/home/thanasis/projects/naturaldoctor/natural-doctor/virtualenv/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 186, in _detect_changes
    self.generate_altered_fields()
  File "/home/thanasis/projects/naturaldoctor/natural-doctor/virtualenv/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 919, in generate_altered_fields
    new_field.remote_field.model._meta.app_label,
AttributeError: 'SettingsReference' object has no attribute '_meta'`

**TECHNICAL DETAILS**
OS: Ubuntu 18.04
Python 3.6.9
Oscar 2.04
Postgres 10

**Comment by solarissmoke** [comment]
This is not originating from Oscar, but from `wagtail-modeltranslation`. See https://github.com/infoportugal/wagtail-modeltranslation/issues/240 .
