### ISSUE TITLE
IntegrityError (1062, "Duplicate entry '00030001' for key 'catalogue_category.path'")

### ISSUE THREAD

**Issue by stanflow** [django-oscar/django-oscar#3525]
### Issue Summary

Thanks for a great shop. Nevertheless ... I'm trying to add a child category at:
/dashboard/catalogue/categories/

I select:
Actions -> Add child category

When I Save the category I get:

```
Exception Type: | IntegrityError
Exception Value: | (1062, "Duplicate entry '00030001' for key 'catalogue_category.path'")
```

```
Traceback (most recent call last):
  File "/home/project/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/project/env/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/project/env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/project/env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/project/env/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)

The above exception ((1062, "Duplicate entry '00030001' for key 'catalogue_category.path'")) was the direct cause of the following exception:
  File "/home/project/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/project/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/project/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/project/env/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 63, in callback
    return old_callback(*args, **kwargs)
  File "/home/project/env/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 63, in callback
    return old_callback(*args, **kwargs)
  File "/home/project/env/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 63, in callback
    return old_callback(*args, **kwargs)
  File "/home/project/env/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 63, in callback
    return old_callback(*args, **kwargs)
  File "/home/project/env/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/project/env/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/project/env/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/project/env/lib/python3.8/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/home/project/env/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/project/env/lib/python3.8/site-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "/home/project/env/lib/python3.8/site-packages/treebeard/forms.py", line 144, in save
    self.instance = reference_node.add_child(**cl_data)
  File "/home/project/env/lib/python3.8/site-packages/treebeard/mp_tree.py", line 1022, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/home/project/env/lib/python3.8/site-packages/treebeard/mp_tree.py", line 389, in process
    newobj.save()
  File "/home/project/env/lib/python3.8/site-packages/oscar/apps/catalogue/abstract_models.py", line 209, in save
    super().save(*args, **kwargs)
  File "/home/project/env/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/project/env/lib/python3.8/site-packages/django/db/models/base.py", line 782, in save_base
    updated = self._save_table(
  File "/home/project/env/lib/python3.8/site-packages/django/db/models/base.py", line 886, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/project/env/lib/python3.8/site-packages/django/db/models/base.py", line 923, in _do_insert
    return manager._insert(
  File "/home/project/env/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/project/env/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/project/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/home/project/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/project/env/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 489, in execute
    return real_execute(self, sql, params)
  File "/home/project/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/project/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/project/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/project/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/project/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/project/env/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/project/env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/project/env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/project/env/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)

Exception Type: IntegrityError at /dashboard/catalogue/categories/create/3
Exception Value: (1062, "Duplicate entry '00030001' for key 'catalogue_category.path'")
```

### Technical details
**Python version:** Python 3.8.2
**Django version:** 3.0
**Oscar version** 2.1

**Comment by solarissmoke** [comment]
I'm not able to reproduce this in the general case. Are you able to provide more details steps to reproduce this, on the [sandbox](https://latest.oscarcommerce.com/) for example? If not it seems likely you're just running into [race conditions](https://github.com/django-treebeard/django-treebeard/issues/53).

**Comment by solarissmoke** [comment]
Closing due to lack of feedback - feel free to reopen if you can provide detailed steps to reproduce.

**Comment by stuaxo** [comment]
Hi, please see the linked case on treebeard.   This happens during heavy writes.   If use two processes doing writes at the same time, you should see it fairly quickly.
