### ISSUE TITLE
ImportError: Not able to import BasketMiddleWare

### ISSUE THREAD

**Issue by devkapilbansal** [django-oscar/django-oscar#3544]
Found a bug? Please fill out the sections below.

### Issue Summary
I tried to use django-oscar and follows the steps given in docs, but I am getting error 
```
ImportError: Module "oscar.apps.basket.middleware" does not define a "BasketMiddleWare" attribute/class
```

The exact traceback I got is:-
```
/home/kapil/Development/___/project/project/project/settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 18, 2020 - 00:11:01
Django version 3.0.10, using settings 'project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/kapil/Development/___/project/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 20, in import_string
    return getattr(module, class_name)
AttributeError: module 'oscar.apps.basket.middleware' has no attribute 'BasketMiddleWare'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kapil/Development/___/project/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/kapil/Development/___/project/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/kapil/Development/___/project/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/home/kapil/Development/___/project/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/kapil/Development/___/project/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 42, in get_internal_wsgi_application
    return get_wsgi_application()
  File "/home/kapil/Development/___/project/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/home/kapil/Development/___/project/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 127, in __init__
    self.load_middleware()
  File "/home/kapil/Development/___/project/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 35, in load_middleware
    middleware = import_string(middleware_path)
  File "/home/kapil/Development/___/project/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 22, in import_string
    raise ImportError('Module "%s" does not define a "%s" attribute/class' % (
ImportError: Module "oscar.apps.basket.middleware" does not define a "BasketMiddleWare" attribute/class

```

### Steps to Reproduce

Follows

1. Follow instructions given at https://django-oscar.readthedocs.io/en/2.1.0/internals/getting_started.html

2. Run python manage.py runserver command after migrate

### Technical details

* Python version: 3.8.5
* Django version: 3.0.10
* Oscar version: 2.1

**Comment by solarissmoke** [comment]
You have a typo: `BasketMiddleWare` is not the same as `BasketMiddleware`
