### ISSUE TITLE
oscar_fork_statics tries to read from non-existant static_src directory

### ISSUE THREAD

**Issue by mslinn** [django-oscar/django-oscar#3651]
Using the current django-oscar, and django, when I try to copy in the default static assets into Frobshop using `oscar_fork_statics` I get an error. Looks like this problem is related to issues #3621 and #3618.
```
$ ./manage.py oscar_fork_statics
System check identified some issues:

WARNINGS:
catalogue.ProductAttributeValue.value_boolean: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
Copying Oscar's static files to /var/work/django/frobshop/static/
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/mslinn/oscar/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/mslinn/oscar/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mslinn/oscar/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mslinn/oscar/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/mslinn/oscar/lib/python3.8/site-packages/oscar/management/commands/oscar_fork_statics.py", line 35, in handle
    shutil.copytree(source, destination)
  File "/usr/lib/python3.8/shutil.py", line 552, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mslinn/oscar/lib/python3.8/site-packages/oscar/static_src'
```

The source directory that `oscar_fork_statics` looks for (`/home/mslinn/oscar/lib/python3.8/site-packages/static_src`) does not exist:
```
$ ls /home/mslinn/oscar/lib/python3.8/site-packages/oscar
__init__.py  apps       core         forms   management  static     templatetags  utils
__pycache__  config.py  defaults.py  locale  models      templates  test          views
```
There is a directory called `static` that seems reasonable, however.

**Comment by mslinn** [comment]
PS: the warning appears every time I run `manage.py`. No idea why. I am sure it is not part of this problem, however.
```
WARNINGS:
catalogue.ProductAttributeValue.value_boolean: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
Copying Oscar's static files to /var/work/django/frobshop/static/
```

**Comment by mslinn** [comment]
PPS: The `oscar_fork_statics` help message does not say the most important thing, unfortunately: the `target_path` must be mentioned in the array of directories specified by `STATICFILES_DIRS` in `settings.py`.

It is unclear to me without being able to run the program whether that means `frobshop/static` or  `frobshop/frobshop/static`, however.
