### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_descendant_of'

### ISSUE THREAD

**Issue by ezimir** [django-oscar/django-oscar#3667]
### Issue Summary

After clean install (just django with django-oscar) using PostreSQL, when creating a child category, I get this error above.

### Steps to Reproduce

1. Install

```bash
$ pip install psycopg2 django django-oscar[sorl-thumbnail]
$ django-admin startproject newshop
$ cd newshop
$ vim newshop/settings.py # with contents of https://django-oscar.readthedocs.io/en/3.0.0/internals/getting_started.html
$ python manage.py migrate
$ python manage.py createsuperuser
$ python manage.py runserver
```

2. open dashboard http://localhost/dashboard/catalogue/categories/create
3. create category "MyCat"
4. create category "Child" as "First child of" "MyCat" (either manually select, or via shortcut from "Actions > Add child category"

I get this:
```
Traceback (most recent call last):
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/treebeard/forms.py", line 145, in save
    self.instance.move(reference_node, pos=position_type)
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/treebeard/mp_tree.py", line 1164, in move
    return MP_MoveHandler(self, target, pos).process()
  File "/home/ezimir/test-eshop/lib/python3.9/site-packages/treebeard/mp_tree.py", line 473, in process
    if self.target.is_descendant_of(self.node):
AttributeError: 'NoneType' object has no attribute 'is_descendant_of'
```

Weird thing is, the object was created, but is not displayed anywhere on dashboard:
```python
$ python manage.py shell
Python 3.9.0 (default, Nov 28 2020, 12:00:13)
[GCC 10.2.0] on linux
>>> from oscar.core.loading import get_model
>>> Category = get_model("catalogue", "Category")
>>> Category.objects.all()
<CategoryQuerySet [<Category: MyCat>, <Category: MyCat > Child>]>
```

If I do the same steps, but with SQLite, categories work as expected.

### Technical details

Python version: 3.9.0
Django version: 3.1.7
Oscar version: 3.0.2
PostgreSQL version: 12.6 (Ubuntu 12.6-0ubuntu0.20.10.1)

**Comment by solarissmoke** [comment]
Looks like you're running into the issue described here: https://github.com/django-treebeard/django-treebeard/issues/174 , which seems to be an issue with how collation is set up on your database.

**Comment by ezimir** [comment]
> Looks like you're running into the issue described here: [django-treebeard/django-treebeard#174](https://github.com/django-treebeard/django-treebeard/issues/174) , which seems to be an issue with how collation is set up on your database.

Seems like it is, thank you.

Would you be able to point me to where I could find the proper settings for this? The issue you linked has an example with actual SELECTs, which I doubt I can influence when using django-oscar. I.e. what would be the proper collation configuration for this to work?

**Comment by ezimir** [comment]
Proper seetings, which I got this to work with, may look like this:

```sql
CREATE DATABASE "newshop"
  WITH OWNER "postgres"
  ENCODING 'UTF8'
  LC_COLLATE = 'en_US.UTF-8'
  LC_CTYPE = 'en_US.UTF-8';
```
via https://stackoverflow.com/a/9963618/62120
