### ISSUE TITLE
How to disable analytics app

### ISSUE THREAD

**Issue by stereoshoots** [django-oscar/django-oscar#3775]
Hello, is there a proper way to disable analytics app? I have no need in analytic tables. Disconnecting receivers (implemented at oscar/app/analytics/receivers.py) in my project seems to be monkey pathcing to me.

Thank you

**Comment by jwayodi** [comment]
Have you tried removing the app from your project's `INSTALLED_APPS` setting?

**Comment by stereoshoots** [comment]
Removed from INSTALLED_APPS. Also removed oscar.apps.dashboard.reports which uses analytics. Still having error 

`KeyError: 'analytics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/src/billing/urls.py", line 5, in <module>
    from oscar.app import application
  File "/usr/local/lib/python3.6/site-packages/oscar/app.py", line 13, in <module>
    class Shop(Application):
  File "/usr/local/lib/python3.6/site-packages/oscar/app.py", line 22, in Shop
    dashboard_app = get_class('dashboard.app', 'application')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 59, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/app.py", line 10, in <module>
    class DashboardApplication(BaseDashboardApplication):
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/app.py", line 17, in DashboardApplication
    reports_app = get_class('dashboard.reports.app', 'application')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 59, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/reports/app.py", line 7, in <module>
    class ReportsApplication(DashboardApplication):
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/reports/app.py", line 11, in ReportsApplication
    index_view = get_class('dashboard.reports.views', 'IndexView')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 59, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/reports/views.py", line 9, in <module>
    ReportForm = get_class('dashboard.reports.forms', 'ReportForm')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 59, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/reports/forms.py", line 8, in <module>
    'GeneratorRepository')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 59, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/reports/utils.py", line 6, in <module>
    'UserReportGenerator'])
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/analytics/reports.py", line 10, in <module>
    ProductRecord = get_model('analytics', 'ProductRecord')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 296, in get_model
    return apps.get_model(app_label, model_name)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 202, in get_model
    app_config = self.get_app_config(app_label)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 159, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'analytics'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 152, in get_app_config
    return self.app_configs[app_label]
KeyError: 'analytics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/src/billing/urls.py", line 5, in <module>
    from oscar.app import application
  File "/usr/local/lib/python3.6/site-packages/oscar/app.py", line 13, in <module>
    class Shop(Application):
  File "/usr/local/lib/python3.6/site-packages/oscar/app.py", line 22, in Shop
    dashboard_app = get_class('dashboard.app', 'application')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 59, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/app.py", line 10, in <module>
    class DashboardApplication(BaseDashboardApplication):
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/app.py", line 17, in DashboardApplication
    reports_app = get_class('dashboard.reports.app', 'application')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 59, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/reports/app.py", line 7, in <module>
    class ReportsApplication(DashboardApplication):
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/reports/app.py", line 11, in ReportsApplication
    index_view = get_class('dashboard.reports.views', 'IndexView')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 59, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/reports/views.py", line 9, in <module>
    ReportForm = get_class('dashboard.reports.forms', 'ReportForm')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 59, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/reports/forms.py", line 8, in <module>
    'GeneratorRepository')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 59, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/reports/utils.py", line 6, in <module>
    'UserReportGenerator'])
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 69, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 127, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 182, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/analytics/reports.py", line 10, in <module>
    ProductRecord = get_model('analytics', 'ProductRecord')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 296, in get_model
    return apps.get_model(app_label, model_name)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 202, in get_model
    app_config = self.get_app_config(app_label)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 159, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'analytics'.`

**Comment by devanao** [comment]
solved it overriding the _ready_ and _get_urls_ methods of DashboardConfig 
Just comment the `self.reports_app = apps.get_app_config('reports_dashboard')` and `path('reports/', include(self.reports_app.urls[0]))` lines

```import oscar.apps.dashboard.apps as dash_apps
from oscar.core.loading import get_class
from django.urls import include, path
from django.apps import apps
class DashboardConfig(dash_apps.DashboardConfig):
    name = 'apps.dashboard'
    def ready(self):
        self.index_view = get_class('dashboard.views', 'IndexView')
        self.login_view = get_class('dashboard.views', 'LoginView')

        self.catalogue_app = apps.get_app_config('catalogue_dashboard')
        # self.reports_app = apps.get_app_config('reports_dashboard')
        self.orders_app = apps.get_app_config('orders_dashboard')
        self.users_app = apps.get_app_config('users_dashboard')
        self.pages_app = apps.get_app_config('pages_dashboard')
        self.partners_app = apps.get_app_config('partners_dashboard')
        self.offers_app = apps.get_app_config('offers_dashboard')
        self.ranges_app = apps.get_app_config('ranges_dashboard')
        self.reviews_app = apps.get_app_config('reviews_dashboard')
        self.vouchers_app = apps.get_app_config('vouchers_dashboard')
        self.comms_app = apps.get_app_config('communications_dashboard')
        self.shipping_app = apps.get_app_config('shipping_dashboard')

    def get_urls(self):
        from django.contrib.auth import views as auth_views

        urls = [
            path('', self.index_view.as_view(), name='index'),
            path('catalogue/', include(self.catalogue_app.urls[0])),
            # path('reports/', include(self.reports_app.urls[0])),
            path('orders/', include(self.orders_app.urls[0])),
            path('users/', include(self.users_app.urls[0])),
            path('pages/', include(self.pages_app.urls[0])),
            path('partners/', include(self.partners_app.urls[0])),
            path('offers/', include(self.offers_app.urls[0])),
            path('ranges/', include(self.ranges_app.urls[0])),
            path('reviews/', include(self.reviews_app.urls[0])),
            path('vouchers/', include(self.vouchers_app.urls[0])),
            path('comms/', include(self.comms_app.urls[0])),
            path('shipping/', include(self.shipping_app.urls[0])),
            path('login/', self.login_view.as_view(), name='login'),
            path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
        ]
        return self.post_process_urls(urls)

**Comment by joeyjurjens** [comment]
Can be solved as said by the latest reply.
