### ISSUE TITLE
Defining `inlineformsets` tie some AbstractModel's fields type to ForeignKey

### ISSUE THREAD

**Issue by amatmv** [django-oscar/django-oscar#3784]
### Issue Summary

We have the `ProductAttribute` model with a ForeignKey relation to `ProductClass`. So an attribute can't be reused among other types of products, which is a little bit of a restriction.

In our project using django-oscar, we want to change that, and change this relation from ForeignKey to a ManyToMany.

**Problem is: How to delete the `product_class` field of ProductAttribute to make the new one named `product_classes`?** 

- Setting the field to None?

```Python
class ProductAttribute(AbstractProductAttribute):
    product_class = None
    product_classes = models.ManyToManyField(
        'catalogue.ProductClass',
        blank=True,
        related_name="attributes",
        verbose_name="Product type"
    )
```

We will try to generate the migrations and will found an error: 
```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/local/app/nilo/dashboard/catalogue/apps.py", line 13, in ready
    self.category_lookup_view = get_class('dashboard.catalogue.views', 'CategoryLookupView')
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 42, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 52, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 110, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 144, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/catalogue/views.py", line 44, in <module>
    'AttributeOptionFormSet'))
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 52, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 110, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/core/loading.py", line 144, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/usr/local/lib/python3.6/site-packages/oscar/apps/dashboard/catalogue/formsets.py", line 155, in <module>
    extra=3)
  File "/usr/local/lib/python3.6/site-packages/django/forms/models.py", line 1053, in inlineformset_factory
    fk = _get_foreign_key(parent_model, model, fk_name=fk_name)
  File "/usr/local/lib/python3.6/site-packages/django/forms/models.py", line 1027, in _get_foreign_key
    parent_model._meta.label,
ValueError: 'catalogue.ProductAttribute' has no ForeignKey to 'catalogue.ProductClass'.
```

As we can see, the field `oscar/apps/dashboard/catalogue/formsets.py` defines an `inlineformset` between ProductClass and ProductAttribute.

```Python
ProductAttributesFormSet = inlineformset_factory(ProductClass,
                                                 ProductAttribute,
                                                 form=ProductAttributesForm,
                                                 extra=3)
```

So, **this forces the ProductAttribute to have to have a FK to ProductClass, without the possibility to change it freely**

How am I supposed to do it then?

### Possible solution

- Maybe change the core relation of django-oscar to be ManyToMany? I could do it if you want.

- Having both fields in the ProductAttribute model?

```Python
class ProductAttribute(AbstractProductAttribute):
    product_classes = models.ManyToManyField(
        'catalogue.ProductClass',
        blank=True,
        related_name="attributes_related",
        verbose_name="Product type"
    )
```
Now we have two fields, but I have to change the related_name of the M2M not to clash with the other.

- Any suggestion?

### Technical details

* Python version: 3.6
* Django version: 2.2.19
* Oscar version: 2.1

**Comment by solarissmoke** [comment]
I think the easiest solution for you would be to:

1. Leave the existing field in place, but redefine it to change it's related name (so that you can use the original related name on your own field).
2. Add a new field to replace yours - and then override the relevant forms/formsets in the dashboard.

I think there is an argument for making the field a many-to-many relation in Oscar itself  - however doing so will require a bit of work to figure out how you then expose this functionality in the dashboard (the current inline formsets would no longer work). Do you have a proposed implementation for that - how are you going to handle it on your project?
