### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by godwnwaswa** [django-oscar/django-oscar#4006]
Found a bug? Please fill out the sections below.

### Issue Summary

I get a warning when I execute manage.py runserver

### Steps to Reproduce

1.  `./manage.py runserver

### Technical details
uring handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\pyzone\venv\lib\site-packages\pysolr.py", line 416, in _send_request
    resp = requests_method(
  File "F:\pyzone\venv\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "F:\pyzone\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\pyzone\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "F:\pyzone\venv\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8983): Max retries exceeded with url: /solr/select/?q=%2A%3A%2A&fl=%2A+score&df=text&start=0&rows=0&spellcheck=true&spellcheck.collate=true&spellcheck.count=1&facet=on&facet.field=product_class_exact&facet.field=rating_exact&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&fq=django_ct%3A%28catalogue.product%29&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001586FE84970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\pyzone\venv\lib\site-packages\haystack\backends\solr_backend.py", line 167, in search
    raw_results = self.conn.search(query_string, **search_kwargs)
  File "F:\pyzone\venv\lib\site-packages\pysolr.py", line 827, in search
    response = self._select(params, handler=search_handler)
  File "F:\pyzone\venv\lib\site-packages\pysolr.py", line 488, in _select
    return self._send_request("get", path)
  File "F:\pyzone\venv\lib\site-packages\pysolr.py", line 431, in _send_request
    raise SolrError(error_message % (url, err))
pysolr.SolrError: Failed to connect to server at http://127.0.0.1:8983/solr/select/?q=%2A%3A%2A&fl=%2A+score&df=text&start=0&rows=0&spellcheck=true&spellcheck.collate=true&spellcheck.count=1&facet=on&facet.field=product_class_exact&facet.field=rating_exact&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&fq=django_ct%3A%28catalogue.product%29&wt=json: HTTPConnectionPool(host='127.0.0.1', port=8983): Max retries exceeded with url: /solr/select/?q=%2A%3A%2A&fl=%2A+score&df=text&start=0&rows=0&spellcheck=true&spellcheck.collate=true&spellcheck.count=1&facet=on&facet.field=product_class_exact&facet.field=rating_exact&facet.query=price_exact%3A%5B0+TO+20%5D&facet.query=price_exact%3A%5B20+TO+40%5D&facet.query=price_exact%3A%5B40+TO+60%5D&facet.query=price_exact%3A%5B60+TO+%2A%5D&fq=django_ct%3A%28catalogue.product%29&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001586FE84970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by godwnwaswa** [comment]
resolved! it was a Solr configuration error
