### ISSUE TITLE
Range Model throws ProgrammingError at /dashboard/ranges/

### ISSUE THREAD

**Issue by mghiglieri** [django-oscar/django-oscar#4049]
### Issue Summary

Opening dashboard/ranges/
ProgrammingError at /shop/dashboard/ranges/
(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'."id" FROM "catalogue_category" AS "CATALOGUE_CATEGORY_BASE"\nLEFT JOIN "catal...\' at line 2')

Adding a voucher to a cart
ProgrammingError at /shop/basket/vouchers/add/
(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'."id" FROM "catalogue_category" AS "CATALOGUE_CATEGORY_BASE"\nLEFT JOIN "catal...\' at line 2')

There seems to be some problems with the JOINS

The error is caused in site-packages/oscar/apps/offer/abstract_models.py, line 952, in num_products

```
>>> Product.objects.filter(Q(categories__in=expanded_range_categories))
Traceback (most recent call last):
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    if self._binary_prefix:
MySQLdb._exceptions.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'."id" FROM "catalogue_category" AS "CATALOGUE_CATEGORY_BASE"\nLEFT JOIN "catal...\' at line 2')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/models/query.py", line 296, in __repr__
    self._sticky_filter = False
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/models/query.py", line 302, in __len__
    self._fields = None
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    FOR UPDATE lock.
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
    return list(islice(gen, self.chunk_size))
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    def has_results(self):
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    if self._binary_prefix:
django.db.utils.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'."id" FROM "catalogue_category" AS "CATALOGUE_CATEGORY_BASE"\nLEFT JOIN "catal...\' at line 2')
```

Does anyone know how to fix it?

Python version: Python 3.8.10
Django version: 4.1.6
django-oscar version: 3.2

**Comment by mghiglieri** [comment]
Have a look in #4050 
This change has fixed my issue.

**Comment by st8st8** [comment]
There's a mildly unpleasant workaround for this here:

https://github.com/django-oscar/django-oscar/commit/4c6643142784e3a49235926da92470867b1d59e8
