### ISSUE TITLE
Building sandbox fails on M1 Mac with recent node/npm, unless `node-sass` package is removed

### ISSUE THREAD

**Issue by TibsAtWork** [django-oscar/django-oscar#4370]
### Issue Summary

Building the sandbox with `make sandbox` (which runs `npm install`) fails when it tries to install `node-sass` on a recent M1 Mac with a recent version of node.

[node-sass](https://www.npmjs.com/package/node-sass) is deprecated and in maintenance mode.  [sass](https://www.npmjs.com/package/sass) is suggested as a replacement, and that's already present in the `package.json` file.

Removing the requirement for `node-sass` from the `package.json` file allows `make sandbox` to complete successfully.

### Steps to Reproduce

I'm on Mac M1 Sonoma 14.7, with Python 3.11.3, node v22.9.0 (using `brew install npm`) and with the xcode command line tools installed (using `xcode-select --install`).

Using either the Oscar branch `releases/3.2.4` or `master`, `make sandbox`.

```
$ cd django-oscar
$ python3 -m venv venv
$ source venv/bin/activate
$ make sandbox
```

Specifically, the `npm install` step fails to install [node-sass](https://www.npmjs.com/package/node-sass), first being unable to find a suitable binary:
```
npm error code 1
npm error path /Users/tony.ibbs/temp/django-oscar-2024-10-16/django-oscar/node_modules/node-sass
npm error command failed
npm error command sh -c node scripts/build.js
npm error Binary found at /Users/tony.ibbs/temp/django-oscar-2024-10-16/django-oscar/node_modules/node-sass/vendor/darwin-arm64-127/binding.node
npm error Testing binary
npm error Binary has a problem: Error: dlopen(/Users/tony.ibbs/temp/django-oscar-2024-10-16/django-oscar/node_modules/node-sass/vendor/darwin-arm64-127/binding.node, 0x0001): tried: '/Users/tony.ibbs/temp/django-oscar-2024-10-16/django-oscar/node_modules/node-sass/vendor/darwin-arm64-127/binding.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/tony.ibbs/temp/django-oscar-2024-10-16/django-oscar/node_modules/node-sass/vendor/darwin-arm64-127/binding.node' (no such file), '/Users/tony.ibbs/temp/django-oscar-2024-10-16/django-oscar/node_modules/node-sass/vendor/darwin-arm64-127/binding.node' (not a mach-o file)
```

and then failing to build `node-sass` from source code, due to a compiler error:
```
npm error In file included from ../src/libsass/src/ast.cpp:1:
npm error ../src/libsass/src/sass.hpp:49:10: fatal error: 'string' file not found
npm error    49 | #include <string>
npm error       |          ^~~~~~~~
npm error 1 error generated.
npm error make[1]: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
```

The documentation for [node-sass](https://www.npmjs.com/package/node-sass) makes it clear that it is deprecated and in maintenance mode, and no further binary releases will be provided. It also suggests using [sass](https://www.npmjs.com/package/sass) instead.

In fact, `sass` is already present in the `package.json` file:
```
    "sass": "^1.78.0",
```

Removing the `node-sass` line from `package.json` and re-doing `make sandbox` (and thus `npm install`) allows the build to succeed, and I can then successfully run up the sandbox shop with `sandbox/manage.py runserver`

### Technical details

* Python version: 3.11.3
* Django version: 5.1.2
* Oscar version: 4.0a1
* Node version: v22.9.0, npm version 10.8.3

**Comment by jmb** [comment]
Thanks, this resolved my sandbox install issue on a Mac M2.

**Comment by jwayodi** [comment]
I created the exact same [PR](https://github.com/django-oscar/django-oscar/pull/4568) before I saw yours, after coming across Node Sass while investigating something else.

I was able to build the sandbox (and install the npm packages, including `node-sass`), but only after fixing an issue with my build environment. By the way, yours seems to be an issue [other people have come across](https://duckdb.org/docs/current/dev/building/macos#build-failure-string-file-not-found).

First was an issue with the `vendor/linux-x64-141/binding.node` binary:

```
error Binary found at /home/chui/projects/oscar/code/django-oscar/node_modules/node-sass/vendor/linux-x64-141/binding.node
error Testing binary
error Binary has a problem: Error: /home/chui/projects/oscar/code/django-oscar/node_modules/node-sass/vendor/linux-x64-141/binding.node: file too short
error     at Object..node (node:internal/modules/cjs/loader:1996:18)
error     at Module.load (node:internal/modules/cjs/loader:1552:32)
error     at Module._load (node:internal/modules/cjs/loader:1354:12)
error     at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
error     at Module.require (node:internal/modules/cjs/loader:1575:12)
error     at require (node:internal/modules/helpers:191:16)
error     at module.exports (/home/chui/projects/oscar/code/django-oscar/node_modules/node-sass/lib/binding.js:19:10)
error     at Object.<anonymous> (/home/chui/projects/oscar/code/django-oscar/node_modules/node-sass/lib/index.js:13:35)
error     at Module._compile (node:internal/modules/cjs/loader:1829:14)
error     at Object..js (node:internal/modules/cjs/loader:1969:10) {
error   code: 'ERR_DLOPEN_FAILED'
error }
error Building the binary locally
error Building: /home/chui/.config/nvm/versions/node/v25.9.0/bin/node /home/chui/projects/oscar/code/django-oscar/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
```

Which required building the binary locally, but `distutils` could not be found (it was removed in Python 3.12), and I had to install `setuptools`, which still provides it:

```
error Traceback (most recent call last):
error   File "/home/chui/projects/oscar/code/django-oscar/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
error     import gyp  # noqa: E402
error     ^^^^^^^^^^
error   File "/home/chui/projects/oscar/code/django-oscar/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
error     import gyp.input
error   File "/home/chui/projects/oscar/code/django-oscar/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
error     from distutils.version import StrictVersion
error ModuleNotFoundError: No module named 'distutils'
```

My environment is:
Oscar version: `master` at `dc6de5a` (after 4.1)
Django version: 6.0.5
Python version: 3.14.4
Node version: v25.9.0, with npm version 11.12.1
OS version: Debian GNU/Linux 13 (trixie)

**Comment by jwayodi** [comment]
As Node Sass rots even further, more users are going to run into different issues installing it. We really should remove it.
