### ISSUE TITLE
Sandbox unicode error when sending email

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#817]
Strangely, the sandbox sometimes raises a unicode error when an email is sent.  I haven't been able to create this - needs more investigation.

``` python
Traceback (most recent call last):

  File "/var/www/oscar/virtualenvs/sandbox/lib/python2.6/site-packages/Django-1.5.2-py2.6.egg/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/var/www/oscar/virtualenvs/sandbox/lib/python2.6/site-packages/Django-1.5.2-py2.6.egg/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)

  File "/var/www/oscar/builds/sandbox/oscar/apps/checkout/session.py", line 24, in dispatch
    return super(CheckoutSessionMixin, self).dispatch(request, *args, **kwargs)

  File "/var/www/oscar/virtualenvs/sandbox/lib/python2.6/site-packages/Django-1.5.2-py2.6.egg/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)

  File "/var/www/oscar/builds/sandbox/oscar/apps/checkout/views.py", line 384, in post
    return self.submit(request.basket)

  File "/var/www/oscar/builds/sandbox/oscar/apps/checkout/views.py", line 558, in submit
    **order_kwargs)

  File "/var/www/oscar/builds/sandbox/oscar/apps/checkout/mixins.py", line 59, in handle_order_placement
    return self.handle_successful_order(order)

  File "/var/www/oscar/builds/sandbox/oscar/apps/checkout/mixins.py", line 89, in handle_successful_order
    self.send_confirmation_message(order)

  File "/var/www/oscar/builds/sandbox/oscar/apps/checkout/mixins.py", line 351, in send_confirmation_message
    event_type, **kwargs)

  File "/var/www/oscar/builds/sandbox/oscar/apps/customer/utils.py", line 42, in dispatch_order_messages
    self.dispatch_user_messages(order.user, messages)

  File "/var/www/oscar/builds/sandbox/oscar/apps/customer/utils.py", line 54, in dispatch_user_messages
    self.send_user_email_messages(user, messages)

  File "/var/www/oscar/builds/sandbox/oscar/apps/customer/utils.py", line 68, in send_user_email_messages
    email = self.send_email_messages(user.email, messages)

  File "/var/www/oscar/builds/sandbox/oscar/apps/customer/utils.py", line 99, in send_email_messages
    email.send()

  File "/var/www/oscar/virtualenvs/sandbox/lib/python2.6/site-packages/Django-1.5.2-py2.6.egg/django/core/mail/message.py", line 255, in send
    return self.get_connection(fail_silently).send_messages([self])

  File "/var/www/oscar/virtualenvs/sandbox/lib/python2.6/site-packages/Django-1.5.2-py2.6.egg/django/core/mail/backends/smtp.py", line 95, in send_messages
    sent = self._send(message)

  File "/var/www/oscar/virtualenvs/sandbox/lib/python2.6/site-packages/Django-1.5.2-py2.6.egg/django/core/mail/backends/smtp.py", line 113, in _send
    force_bytes(message.as_string(), charset))

  File "/var/www/oscar/virtualenvs/sandbox/lib/python2.6/site-packages/Django-1.5.2-py2.6.egg/django/core/mail/message.py", line 169, in as_string
    g.flatten(self, unixfrom=unixfrom)

  File "/usr/lib/python2.6/email/generator.py", line 84, in flatten
    self._write(msg)

  File "/usr/lib/python2.6/email/generator.py", line 109, in _write
    self._dispatch(msg)

  File "/usr/lib/python2.6/email/generator.py", line 135, in _dispatch
    meth(msg)

  File "/usr/lib/python2.6/email/generator.py", line 201, in _handle_multipart
    g.flatten(part, unixfrom=False)

  File "/usr/lib/python2.6/email/generator.py", line 84, in flatten
    self._write(msg)

  File "/usr/lib/python2.6/email/generator.py", line 109, in _write
    self._dispatch(msg)

  File "/usr/lib/python2.6/email/generator.py", line 135, in _dispatch
    meth(msg)

  File "/usr/lib/python2.6/email/generator.py", line 178, in _handle_text
    self._fp.write(payload)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 158-159: ordinal not in range(128)


<WSGIRequest
path:/checkout/preview/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'action': [u'place_order'], u'csrfmiddlewaretoken': [u'aulvLYkPdci6bcVeqixjpol1LmczY1Ut']}>,
COOKIES:{'csrftoken': 'aulvLYkPdci6bcVeqixjpol1LmczY1Ut',
 'oscar_recently_viewed_products': '[231]',
 'sessionid': 'nphzmehw8wh6t1ovbsayhjeooaoev6h9'},
META:{'CONTENT_LENGTH': '71',
 'CONTENT_TYPE': 'application/x-www-form-urlencoded',
 u'CSRF_COOKIE': u'aulvLYkPdci6bcVeqixjpol1LmczY1Ut',
 'DOCUMENT_ROOT': '/var/www/nginx-default',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'csrftoken=aulvLYkPdci6bcVeqixjpol1LmczY1Ut; oscar_recently_viewed_products="[231]"; sessionid=nphzmehw8wh6t1ovbsayhjeooaoev6h9',
 'HTTP_HOST': 'latest.oscarcommerce.com',
 'HTTP_REFERER': 'http://latest.oscarcommerce.com/checkout/preview/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:23.0) Gecko/20100101 Firefox/23.0',
 'HTTP_X_FORWARDED_FOR': '37.191.99.202',
 'HTTP_X_REAL_IP': '37.191.99.202',
 'PATH': '/usr/local/bin:/usr/bin:/bin',
 'PATH_INFO': u'/checkout/preview/',
 'PATH_TRANSLATED': '/var/www/oscar/builds/sandbox/sites/sandbox/deploy/wsgi/sandbox.wsgi/checkout/preview/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '37.191.99.202',
 'REMOTE_PORT': '38538',
 'REQUEST_METHOD': 'POST',
 'REQUEST_URI': '/checkout/preview/',
 'SCRIPT_FILENAME': '/var/www/oscar/builds/sandbox/sites/sandbox/deploy/wsgi/sandbox.wsgi',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '127.0.0.1',
 'SERVER_ADMIN': '[no address given]',
 'SERVER_NAME': 'latest.oscarcommerce.com',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.2.14 (Ubuntu) mod_wsgi/2.8 Python/2.6.5',
 'mod_wsgi.application_group': '',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '81',
 'mod_wsgi.process_group': 'oscar',
 'mod_wsgi.reload_mechanism': '1',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (2, 8),
 'wsgi.errors': <mod_wsgi.Log object at 0x7f524d555090>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f524d707cd8>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f524d5ecb70>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

**Comment by sasha0** [comment]
Closing since the issue did not occur for a while.
